  version: '3'

  services:

#    laravel:
#      container_name: cafetime_api
#      image: php:8.0.0RC5-fpm-alpine3.12
#      restart: always
#      working_dir: ${LARAVEL_PATH_CONTAINER}
#      volumes:
#        - ${LARAVEL_PATH_HOST}:${LARAVEL_PATH_CONTAINER}
#      depends_on:
#        - postgresdb
#        - redisdb

    postgresdb:
      container_name: cafetime_postgresdb
      image: postgres:9.6.20
      restart: always
      ports:
        - 127.0.0.1:5432:5432
      environment:
        - POSTGRES_DB=cafetime
        - POSTGRES_USER=cafetime
        - POSTGRES_PASSWORD=pass
      volumes:
        - ./postgresql-data:/var/lib/postgresql/data

    redisdb:
      container_name: cafetime_redisdb
      image: redis:6.0.9
      restart: always
      ports:
        - 127.0.0.1:6379:6379
      volumes:
        - ./redis-data:/data

    adminer:
      container_name: cafetime_adminer
      image: adminer:4.7.7
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - postgresdb