  version: '3'

  services:

#    laravel:
#      container_name: breaktime_api
#      image: php:8.0.0RC5-fpm-alpine3.12
#      restart: always
#      working_dir: ${LARAVEL_PATH_CONTAINER}
#      volumes:
#        - ${LARAVEL_PATH_HOST}:${LARAVEL_PATH_CONTAINER}
#      depends_on:
#        - postgresdb
#        - redisdb

    postgresdb:
      container_name: breaktime_postgresdb
      image: postgres:14.2
      restart: always
      ports:
        - "127.0.0.1:5432:5432"
      environment:
        - POSTGRES_DB=cafetime
        - POSTGRES_USER=cafetime
        - POSTGRES_PASSWORD=pass
      volumes:
        - ./.docker/postgresql-data:/var/lib/postgresql/data

    redisdb:
      container_name: breaktime_redisdb
      image: redis:6.2.6
      restart: always
      ports:
        - "127.0.0.1:6379:6379"
      volumes:
        - ./.docker/redis-data:/data
